trigger:
  branches:
    include:
      - main

variables:
  VM_IP_PUBLICA: '40.123.52.166'
  IMAGE_NAME: 'myapp-nginx-s4'
  ACR_NAME: 'RCMyAppDevops'
  ACR_USERNAME: 'RCMyAppDevops'
  ACR_PASSWORD: 'v1jGxdR+K2CrEq3+Zl82odZCf3CfAxayjPGSfr9+wE+ACRB5cDp6'

stages:
  - stage: Deploy
    jobs:
      - deployment: DeployToVM
        displayName: 'Deploy to VM'
        environment:
          name: 'VM-DevOps-S4'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    if ! command -v az &> /dev/null; then
                      echo "Azure CLI no está instalado. Instalando Azure CLI..."
                      sudo apt-get update && \
                      sudo apt-get install -y curl && \
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
                      az --version || { echo "Error instalando Azure CLI" >&2; exit 1; }
                    else
                      echo "Azure CLI ya está instalado."
                    fi
                  displayName: 'Verificar e Instalar Azure CLI'
                  failOnStderr: true

                - script: |
                    if ! command -v docker &> /dev/null; then
                      echo "Docker no está instalado. Instalando Docker..."
                      export DEBIAN_FRONTEND=noninteractive && \
                      sudo apt-get update && \
                      sudo apt-get install -y \
                        apt-transport-https \
                        ca-certificates \
                        curl \
                        gnupg \
                        lsb-release && \
                      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
                      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
                      sudo apt-get update && \
                      sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
                      sudo systemctl start docker && \
                      sudo systemctl enable docker && \
                      sudo docker --version || { echo "Error instalando Docker" >&2; exit 1; }
                    else
                      echo "Docker ya está instalado."
                    fi
                  displayName: 'Verificar e Instalar Docker'
                  failOnStderr: true

                - script: |
                    echo "Autenticándose en Azure Container Registry y ejecutando la imagen Docker..."
                    echo ${ACR_PASSWORD} | sudo docker login ${ACR_NAME}.azurecr.io -u ${ACR_USERNAME} --password-stdin > /dev/null 2>&1 || { echo "Error autenticándose en ACR" >&2; exit 1; }

                    sudo docker pull ${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest || { echo "Error descargando la imagen Docker" >&2; exit 1; }

                    if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^nginx_container\$"; then
                      echo "El contenedor 'nginx_container' ya existe. Iniciándolo nuevamente..."
                      sudo docker start nginx_container
                    else
                      echo "El contenedor 'nginx_container' no existe. Creándolo y ejecutándolo..."
                      sudo docker run -d -p 80:80 --name nginx_container ${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest || { echo "Error ejecutando el contenedor Docker" >&2; exit 1; }
                    fi

                    sudo docker ps
                  displayName: 'Descargar y ejecutar la imagen Nginx desde ACR'
                  failOnStderr: true

                - script: |
                    echo "La URL para acceder a Nginx es: http://${VM_IP_PUBLICA}/"
                  displayName: 'Mostrar URL de la máquina virtual'